version: 2
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/circleci-java
    steps:
      - checkout
      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run: ./mvnw clean verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
orbs:
  prometheus: prometheus/prometheus@0.11.0
